[build]
  command = "echo Building for Netlify"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = "*"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/home"
  status = 200
[[redirects]]
  from = "/comments"
  to = "/.netlify/functions/comments"
  status = 200
[[redirects]]
  from = "/users"
  to = "/.netlify/functions/users/"
  status = 200
