[build]
  command = "echo Building for Netlify"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "https://bestservedcold.netlify.app/, *"
        Access-Control-Allow-Headers = "*"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/home"
[[redirects]]
  from = "/comments"
  to = "/.netlify/functions/comments"
